[build]
command = "npm run build"
publish = "dist"

# Redirect HTTP to HTTPS for custom domain
[[redirects]]
from = "http://flipagif.com/*"
to = "https://flipagif.com/:splat"
status = 301
force = true

# Ensure www redirects to non-www
[[redirects]]
from = "https://www.flipagif.com/*"
to = "https://flipagif.com/:splat"
status = 301
force = true
